language: php

php:
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml test

after_script:
  - php vendor/bin/coveralls -v

notifications:
  emails:
    - tadatoshi.tokutake@gmail.com
  on_success: change
  on_failure: always
